# Generated by Django 6.0.3 on 2026-04-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField()),
                ('dob', models.DateField()),
                ('gender', models.CharField()),
                ('username', models.CharField()),
                ('password', models.CharField()),
                ('address', models.CharField()),
                ('country', models.CharField()),
                ('agree', models.CharField()),
            ],
        ),
    ]
